name: run-github-action-from-slack

on:
  repository_dispatch:
    types: on-zmessage-in-slack-channel
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  github-actions-trigger-from-slack-message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, I have run because I got the command from slack!
